### ISSUE TITLE
怎么设置 locale

### ISSUE THREAD

**Issue by JeffreyBool** [bytedance/bytemd#61]

**Comment by JeffreyBool** [comment]
还有不能拿到 html 内容吗

**Comment by pd4d10** [comment]
```js
import zhHans from 'bytemd/lib/locales/zh_Hans.json'

<Editor
  locale={zhHans}
/>
```

**Comment by JeffreyBool** [comment]
vue咋用------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月22日(星期一) 晚上8:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bytedance/bytemd] 怎么设置 locale (#61)

**Comment by JeffreyBool** [comment]
> ```js
> import zhHans from 'bytemd/lib/locales/zh_Hans.json'
> 
> <Editor
>   locale={zhHans}
> />
> ```

还有不能拿到 html 内容吗
